### ISSUE TITLE
Guidance on creating an individual from an ontology.

### ISSUE THREAD

**Issue by nojaf** [dotnetrdf/docs#2]
Hello, I'm very new to RDF, OWL and this library.
I was reading up on https://dotnetrdf.org/docs/stable/user_guide/Ontology-API.html and I have a question on creating instances.

What I'm trying to achieve it creating a new graph with some instances based on our existing ontology.
I now have something like:
```fsharp
#r "nuget: dotNetRDF"

open VDS.RDF
open VDS.RDF.Ontology
open VDS.RDF.Parsing

// load our existing turtle file
let ontoGraph = new OntologyGraph()
FileLoader.Load(ontoGraph, @"OurOntology.ttl")

// find my class type
let nodeUri= ontoGraph.GetUriNode(UriFactory.Create("http://ourcopony.com/domain#ClassName")) :> INode
let node : Individual = ontoGraph.CreateIndividual(networkNodeUri)
```

Now I'm a little stuck what to do with this node? Do I create a new graph and add it somehow?
I'd like to create a new turtle file based my new data.

Thanks in advance.

**Comment by kal** [comment]
Hi Florian,

The CreateIndividual method will actually create that node in the graph for you - so there is no need to add it. There is also an override that takes a second INode property that allows you to assert the type of the individual you are creating. So you should be able to also do:

```fsharp
let node: Individual = ontoGraph.CreateIndividual(networkNodeUri, nodeUri)
```

Once you have populated your OntologyGraph with data you can just write it out to a Turtle file like any normal IGraph instance - see https://dotnetrdf.org/docs/2.7.x/user_guide/Writing-RDF.html for some examples.

Hope this helps!
